on:
  workflow_run:
    workflows: ["ci-prod"]
    types:
      - completed
jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build da imagem
        run: docker build -t humanconsulting/websocket-application:latest .

      - name: Login no Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin

      - name: Push da imagem
        run: docker push humanconsulting/websocket-application:latest